spring:
  profiles:
    include:
      - rds
    active: local

logging:
  path: logs/devbeginner-news-admin/
---
spring.profiles: local
spring.profiles.include: admin-oauth
spring:
  devtools:
    livereload:
#      enabled: true
  mustache:
    cache: false
server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: devbeginner-news-ssl
  port: 8443

