spring:
  profiles.active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
    open-in-view: false
  session:
    store-type: jdbc
  datasource:
    hikari:
      auto-commit: false

logging:
  path: logs/devbeginner-news-web/
---
spring.profiles.include: local-oauth
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
  mustache:
    cache: false
  resources:
    cache:
      period: 0
  h2:
    console.settings.trace: false
    console:
      enabled: true
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update

---
spring.profiles.include: real-db, local-oauth
spring:
  profiles: local-real
  devtools:
    livereload:
      enabled: true
  mustache:
    cache: false
  resources:
    cache:
      period: 0
  jpa:
    show-sql: true
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      idleTimeout: 600000      #10m
      maxLifetime: 1800000     #30m
      minimumIdle: 4
      maximumPoolSize: 15
      data-source-properties:
        connect-timeout: 30000
        socket-timeout: 60000
---
spring.profiles.include: real-db, real-oauth
spring:
  profiles: real

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      idleTimeout: 600000      #10m
      maxLifetime: 1800000     #30m
      minimumIdle: 4
      maximumPoolSize: 15
      data-source-properties:
        connect-timeout: 30000
        socket-timeout: 60000

