spring:
  profiles.active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:10000}
    open-in-view: false

logging:
  path: logs/devbeginner-news-web/
---
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
  mustache:
    cache: false
  h2:
    console.settings.trace: false
    console:
      enabled: true
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8443
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: devbeginner-news-web
