spring:
  profiles:
    include:
      - rds
    active: local
  batch.job.names: ${job.name:NONE}

logging.level:
  com.woowabros: debug
  org.hibernate.SQL: debug
  org.springframework.batch.item.database.JpaItemWriter: debug
  org.springframework.jdbc.core.JdbcTemplate: info

---
spring:
  profiles: local


---
spring.profiles: local-real
spring.profiles.include:
  - rds
  - real-db

---
spring:
  profiles: real